name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"

    steps:
    - name: "Checkout"
      uses: actions/checkout@v1
    - name: "Install PHP"
      uses: "shivammathur/setup-php@v2"
      with:
         coverage: "none"
         php-version: "${{ matrix.php-version }}"
    - name: composer install
      run: composer install --ansi --no-interaction --no-progress --prefer-dist
    - name: composer test
      run: composer test
    - name: codecov
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
